# config.properties
# OpenAI API Key
API_KEY=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
